//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Mshopkeeper02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerCategory()
        {
            this.Customer = new HashSet<Customer>();
            this.CustomerCategory1 = new HashSet<CustomerCategory>();
        }
    
        public System.Guid CustomerCategoryID { get; set; }
        public string CustomerCategoryCode { get; set; }
        public string CustomerCategoryName { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string Descripton { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCategory> CustomerCategory1 { get; set; }
        public virtual CustomerCategory CustomerCategory2 { get; set; }
    }
}
