//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Mshopkeeper02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItemProperty
    {
        public System.Guid InventoryItemID { get; set; }
        public string ColorCode { get; set; }
        public string SizeCode { get; set; }
        public string SKUPropCode { get; set; }
        public string ItemPropName { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual InventoryItem InventoryItem { get; set; }
        public virtual Size Size { get; set; }
    }
}
