//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Mshopkeeper02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryItem()
        {
            this.InventoryItemProperties = new HashSet<InventoryItemProperty>();
            this.RefDetails = new HashSet<RefDetail>();
        }
    
        public System.Guid InventoryItemID { get; set; }
        public Nullable<System.Guid> InventoryItemCategoryID { get; set; }
        public string SKUCode { get; set; }
        public string BarCode { get; set; }
        public string IventoryItemName { get; set; }
        public string IventoryItemNameAbbr { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> MinimumStock { get; set; }
        public Nullable<int> MaximumStock { get; set; }
        public Nullable<System.Guid> StockID { get; set; }
        public string ShowLocation { get; set; }
        public Nullable<bool> ShowInMenu { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemProperty> InventoryItemProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefDetail> RefDetails { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual InventoryItemCategory InventoryItemCategory { get; set; }
    }
}
