//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Mshopkeeper02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reckoning : DAL.EntityBase
    {
        public System.Guid Id { get; set; }
        public string VoucherId { get; set; }
        public string InvoiceCode { get; set; }
        public string ObjectCode { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> PaidNumber { get; set; }
        public Nullable<decimal> Pay { get; set; }
        public string Explain { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
